server:
  port: 8090

spring:
  application:
    name: servicio-tecnico-service

  datasource:
    url: jdbc:mysql://mysql:3306/serviciotecnicodb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-server:8761/eureka/