server:
  port: 8085

spring:
  application:
    name: usuario-service

  datasource:
    url: jdbc:mysql://mysql:3306/usuariodb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false
