spring.application.name=financiamiento-service

server.port=8098

spring.datasource.url=jdbc:mysql://mysql:3306/financiamientodb

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration