server:
  port: 8091

spring:
  application:
    name: marca-service

  datasource:
    url: jdbc:mysql://mysql:3306/marcadb
    username: root
    password: root

    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/